import React, { useMemo, useState } from 'react';

function toGCalDate(date) {
  // Returns YYYYMMDDTHHMMSSZ in UTC
  const pad = (n) => String(n).padStart(2, '0');
  const y = date.getUTCFullYear();
  const m = pad(date.getUTCMonth() + 1);
  const d = pad(date.getUTCDate());
  const h = pad(date.getUTCHours());
  const min = pad(date.getUTCMinutes());
  const s = pad(date.getUTCSeconds());
  return `${y}${m}${d}T${h}${min}${s}Z`;
}

function buildRecurrence(freq) {
  switch (freq) {
    case 'daily':
      return 'RRULE:FREQ=DAILY;INTERVAL=1';
    case 'weekday':
      return 'RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR';
    case 'every2':
      return 'RRULE:FREQ=DAILY;INTERVAL=2';
    case 'weekly':
      return 'RRULE:FREQ=WEEKLY;INTERVAL=1';
    default:
      return undefined;
  }
}

export default function PlanScheduler({ analysis }) {
  const [title, setTitle] = useState('FaceSenate Improvement Plan');
  const [freq, setFreq] = useState('weekday');
  const [duration, setDuration] = useState(30); // minutes

  const nextStart = useMemo(() => {
    const d = new Date();
    d.setMinutes(d.getMinutes() + 10); // start soon
    d.setSeconds(0);
    d.setMilliseconds(0);
    return d;
  }, []);

  const gcalUrl = useMemo(() => {
    const start = new Date(nextStart);
    const end = new Date(start.getTime() + duration * 60000);
    const dates = `${toGCalDate(start)}/${toGCalDate(end)}`;
    const recur = buildRecurrence(freq);
    const params = new URLSearchParams({
      action: 'TEMPLATE',
      text: title,
      details: `Auto-generated by FaceSenate. ${analysis ? `Your current score: ${analysis.score}.` : ''}`,
      dates,
    });
    if (recur) params.set('recur', recur);
    return `https://calendar.google.com/calendar/render?${params.toString()}`;
  }, [title, freq, duration, nextStart, analysis]);

  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
      <div className="mb-4">
        <h3 className="text-lg font-semibold">Create Your Custom Plan</h3>
        <p className="text-sm text-gray-500">Send recurring reminders to your Google Calendar</p>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <div className="space-y-2">
          <label className="text-sm font-medium text-gray-700">Title</label>
          <input
            className="w-full rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        </div>
        <div className="space-y-2">
          <label className="text-sm font-medium text-gray-700">Frequency</label>
          <select
            className="w-full rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            value={freq}
            onChange={(e) => setFreq(e.target.value)}
          >
            <option value="daily">Every day</option>
            <option value="weekday">Every weekday</option>
            <option value="every2">Every 2 days</option>
            <option value="weekly">Weekly</option>
          </select>
        </div>
        <div className="space-y-2">
          <label className="text-sm font-medium text-gray-700">Duration (minutes)</label>
          <input
            type="number"
            min={10}
            max={180}
            className="w-full rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            value={duration}
            onChange={(e) => setDuration(Number(e.target.value) || 30)}
          />
        </div>
      </div>

      <div className="mt-4 flex flex-wrap items-center justify-between gap-3">
        <div className="text-xs text-gray-500">Starts: {nextStart.toLocaleString()}</div>
        <a
          href={gcalUrl}
          target="_blank"
          rel="noreferrer"
          className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-white transition hover:bg-indigo-700"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>
          Add to Google Calendar
        </a>
      </div>
    </div>
  );
}
